name: CI

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        id: hello
        uses: ./
        with:
          who-to-greet: "John Doe"

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
